import { TableHeaderInfo } from '@commonDefine/common.define';


export const PROJECT_USER_HEADER:TableHeaderInfo[] = [
  {
    content:'PMS.UserName',
    left:false,
    right:false,
    align:'center',
    width:50,
    key:'user_name'
  },
  {
    content:'PMS.EmployeeId',
    left:false,
    right:false,
    align:'center',
    width:50,
    key:'employee_id'
  },
  {
    content:'PMS.Email',
    left:false,
    right:false,
    align:'center',
    width:50,
    key:'email'
  },
  {
    content:'PMS.ProjectRole',
    left:false,
    right:false,
    align:'center',
    width:50,
    key:'project_roleDescription'
  },
  {
    content:'PMS.JiraRole',
    left:false,
    right:false,
    align:'center',
    width:50,
    key:'jira_roleDescription'
  },
  {
    content:'PMS.JiraAccount',
    left:false,
    right:false,
    align:'center',
    width:50,
    key:'jira_user_id'
  },
]
