spring:
  profiles:
#    注意使用active 指定要使用的profiles
    active: dev
---
spring:
#  profiles: dev
  application:
#    应用的名称 可选
    name: waimai
  datasource:
    druid:
#      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.221.95.189:3306/mybatis?serverTimezone=UTC
      username: mybatis
      password: 3363787543
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://124.221.95.189:3306/mybatis?serverTimezone=UTC
#    username: mybatis
#    password: 3363787543
# 配置日志
mybatis-plus:
  configuration:
#    映射实体或者属性时, 将数据库中的表名和字段名中的下划线去掉,按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
---
spring:
  profiles: dev
server:
  port: 8080
  servlet:
    context-path: /dev

---
spring:
  profiles: qas
server:
  port: 8081
  servlet:
    context-path: /qas
---
spring:
  profiles: prod
server:
  port: 8082
  servlet:
    context-path: /prod
---

