import { TableHeaderInfo } from "@commonDefine/common.define";
export type TableCellInfo = Pick<TableHeaderInfo,'content'|'left'|"right"|'align'>

export const JIRA_USER_TABLE_HEADER: TableHeaderInfo[] = [
  {
    align:'center',
    width:70,
    content:'#',
    left:true,
    right:false,
    key:'index'
  },
  {
    width:100,
    content:'common.OPERATION',
    left:true,
    right:false,
    align:'center',
    key:'operation'
  },
  {
    width:70,
    content:'PMS.Id',
    left:false,
    right:false,
    align:'center',
    key:'id'
  },
  {
    width:150,
    content:'PMS.UserName',
    left:false,
    right:false,
    align:'center',
    key:'user_name'
  },
  {
    width:120,
    content:'PMS.EmployeeId',
    left:false,
    right:false,
    align:'center',
    key:'employee_id'
  },
  {
    width:300,
    content:'PMS.Email',
    left:false,
    right:false,
    align:'center',
    key:'email'
  },
  {
    width:100,
    content:'PMS.Division',
    left:false,
    right:false,
    align:'center',
    key:'division'

  },
  {
    width:100,
    content:'JIRAUSER.Status',
    left:false,
    right:false,
    align:'center',
    key:'statusDescription'
  },
  {
    content:'PMS.CreateDate',
    left:false,
    right:false,
    align:'center',
    width:200,
    key:'create_date'
  },
  {
    content:'PMS.DeletedDate',
    left:false,
    right:false,
    align:'center',
    width:200,
    key:'deleted_date'
  },
  {
    width:120,
    content:'JIRAUSER.OrgRole',
    left:false,
    right:false,
    align:'center',
    key:'org_roleDescription'
  },
  {
    width:600,
    content:'JIRAUSER.ProjectList',
    left:false,
    right:false,
    align:'center',
    key:'projects'
  },

]
